import type { EvidenceGroupCode } from "../services/evidence-upload.service";

export type EvidenceAxis = "Ambiental" | "Bioeconomia" | "Social" | "Governança";
export type StrategicObjective = "Certificação Sustentável" | "Bioeconomia Circular" | "Inovação Sustentável" | "Captação de Investimentos" | "GEE / Scope 3";

export interface AgroEvidence {
  id: string;
  name: string;
  expectedDocument: string;
  groupCode: EvidenceGroupCode;
  acceptedTypes: string[];
  primaryAxis: EvidenceAxis;
  scoringAxes: EvidenceAxis[];
  points: 1 | 2 | 3;
  strategicObjectives: StrategicObjective[];
  gapIfMissing: string;
  recommendedService: string;
}

export type EvidenceDocumentMock = AgroEvidence;

const pdf = ["PDF"];
const pdfImage = ["PDF", "JPG", "PNG"];
const office = ["PDF", "DOC", "DOCX", "XLS", "XLSX"];

export const agroEvidences: AgroEvidence[] = [
  { id: "EV01", name: "Licenciamento e regularidade ambiental", expectedDocument: "Licença, autorização, dispensa ou certidão", groupCode: "A", acceptedTypes: pdf, primaryAxis: "Ambiental", scoringAxes: ["Ambiental", "Governança"], points: 3, strategicObjectives: ["Certificação Sustentável"], gapIfMissing: "Lacuna crítica de conformidade", recommendedService: "Regularização ambiental" },
  { id: "EV02", name: "Política ambiental", expectedDocument: "Política ambiental, diretrizes ou manual", groupCode: "F", acceptedTypes: office, primaryAxis: "Ambiental", scoringAxes: ["Ambiental", "Governança"], points: 2, strategicObjectives: ["Certificação Sustentável"], gapIfMissing: "Ausência de diretriz formal", recommendedService: "Estruturação de política ESG" },
  { id: "EV03", name: "Metas e plano ambiental", expectedDocument: "Plano ambiental, metas ou cronograma", groupCode: "C", acceptedTypes: office, primaryAxis: "Ambiental", scoringAxes: ["Ambiental", "Governança", "Bioeconomia"], points: 3, strategicObjectives: ["Certificação Sustentável", "Bioeconomia Circular"], gapIfMissing: "Falta de planejamento ambiental", recommendedService: "Plano de gestão ambiental" },
  { id: "EV04", name: "Gestão de água", expectedDocument: "Contas, indicadores, plano hídrico ou registros de consumo", groupCode: "C", acceptedTypes: office, primaryAxis: "Ambiental", scoringAxes: ["Ambiental", "Bioeconomia"], points: 2, strategicObjectives: ["Bioeconomia Circular"], gapIfMissing: "Falta de mensuração/gestão", recommendedService: "Programa de eficiência hídrica" },
  { id: "EV05", name: "Gestão de energia", expectedDocument: "Contas, indicadores, registros ou plano energético", groupCode: "C", acceptedTypes: office, primaryAxis: "Ambiental", scoringAxes: ["Ambiental", "Bioeconomia"], points: 2, strategicObjectives: ["GEE / Scope 3", "Bioeconomia Circular"], gapIfMissing: "Falta de mensuração/gestão", recommendedService: "Eficiência energética" },
  { id: "EV06", name: "Inventário de GEE", expectedDocument: "Inventário, relatório de emissões ou memória de cálculo", groupCode: "C", acceptedTypes: office, primaryAxis: "Ambiental", scoringAxes: ["Ambiental", "Governança", "Bioeconomia"], points: 3, strategicObjectives: ["GEE / Scope 3"], gapIfMissing: "Lacuna crítica de mensuração", recommendedService: "Elaboração de Inventário GEE" },
  { id: "EV07", name: "Dados para cálculo de emissões", expectedDocument: "Dados de energia, combustíveis, transporte ou resíduos", groupCode: "C", acceptedTypes: office, primaryAxis: "Ambiental", scoringAxes: ["Ambiental", "Bioeconomia"], points: 2, strategicObjectives: ["GEE / Scope 3"], gapIfMissing: "Falta de dados primários", recommendedService: "Estruturação de coleta de dados GEE" },
  { id: "EV08", name: "Plano de redução de GEE", expectedDocument: "Metas, plano de descarbonização ou ações", groupCode: "C", acceptedTypes: office, primaryAxis: "Ambiental", scoringAxes: ["Ambiental", "Governança", "Bioeconomia"], points: 3, strategicObjectives: ["GEE / Scope 3"], gapIfMissing: "Não há estratégia de redução", recommendedService: "Plano de descarbonização" },
  { id: "EV09", name: "Dados da cadeia para Scope 3", expectedDocument: "Dados de fornecedores, logística ou compras", groupCode: "G", acceptedTypes: office, primaryAxis: "Ambiental", scoringAxes: ["Ambiental", "Social", "Governança", "Bioeconomia"], points: 3, strategicObjectives: ["GEE / Scope 3"], gapIfMissing: "Baixa rastreabilidade da cadeia", recommendedService: "Diagnóstico/estruturação Scope 3" },
  { id: "EV10", name: "Gestão de resíduos", expectedDocument: "PGRS, registros ou procedimentos", groupCode: "C", acceptedTypes: office, primaryAxis: "Ambiental", scoringAxes: ["Ambiental", "Governança", "Bioeconomia"], points: 3, strategicObjectives: ["Bioeconomia Circular"], gapIfMissing: "Falta de estrutura de gestão", recommendedService: "Estruturação de gestão de resíduos" },
  { id: "EV11", name: "Comprovantes de destinação", expectedDocument: "MTR, notas, certificados ou registros", groupCode: "D", acceptedTypes: office, primaryAxis: "Bioeconomia", scoringAxes: ["Ambiental", "Governança", "Bioeconomia"], points: 2, strategicObjectives: ["Certificação Sustentável", "Bioeconomia Circular"], gapIfMissing: "Não comprova destinação", recommendedService: "Rastreabilidade de resíduos" },
  { id: "EV12", name: "Reaproveitamento/valorização de resíduos", expectedDocument: "Registros, contratos, fotos ou indicadores", groupCode: "D", acceptedTypes: office, primaryAxis: "Bioeconomia", scoringAxes: ["Ambiental", "Bioeconomia"], points: 3, strategicObjectives: ["Bioeconomia Circular"], gapIfMissing: "Potencial circular não demonstrado", recommendedService: "Projeto de valorização de resíduos" },
  { id: "EV13", name: "Logística reversa", expectedDocument: "Contratos, comprovantes, registros ou sistema de retorno", groupCode: "D", acceptedTypes: office, primaryAxis: "Bioeconomia", scoringAxes: ["Ambiental", "Social", "Governança", "Bioeconomia"], points: 2, strategicObjectives: ["Bioeconomia Circular"], gapIfMissing: "Ausência de rastreabilidade reversa", recommendedService: "Estruturação de logística reversa" },
  { id: "EV14", name: "Estudo de ACV", expectedDocument: "Estudo de ACV, relatório técnico ou análise simplificada", groupCode: "D", acceptedTypes: office, primaryAxis: "Bioeconomia", scoringAxes: ["Ambiental", "Governança", "Bioeconomia"], points: 2, strategicObjectives: ["Bioeconomia Circular", "Inovação Sustentável"], gapIfMissing: "Não mensura impactos do ciclo de vida", recommendedService: "Estudo de ACV" },
  { id: "EV15", name: "Dados para ACV", expectedDocument: "Dados de insumos, energia, transporte ou resíduos", groupCode: "D", acceptedTypes: office, primaryAxis: "Bioeconomia", scoringAxes: ["Ambiental", "Bioeconomia"], points: 2, strategicObjectives: ["Bioeconomia Circular"], gapIfMissing: "Dados insuficientes para ACV", recommendedService: "Estruturação de base de dados para ACV" },
  { id: "EV16", name: "Modelo/prática de economia circular", expectedDocument: "Plano, fluxograma ou modelo de negócio", groupCode: "D", acceptedTypes: office, primaryAxis: "Bioeconomia", scoringAxes: ["Ambiental", "Governança", "Bioeconomia"], points: 3, strategicObjectives: ["Bioeconomia Circular"], gapIfMissing: "Circularidade não estruturada", recommendedService: "Estratégia de Bioeconomia Circular" },
  { id: "EV17", name: "Uso de matérias-primas biológicas", expectedDocument: "Registros de origem, especificações ou compras", groupCode: "D", acceptedTypes: office, primaryAxis: "Bioeconomia", scoringAxes: ["Ambiental", "Bioeconomia"], points: 3, strategicObjectives: ["Bioeconomia Circular"], gapIfMissing: "Não demonstra uso de recursos renováveis", recommendedService: "Estratégia de bioeconomia" },
  { id: "EV18", name: "Bioinsumos/soluções biológicas", expectedDocument: "Registros de uso, compras, fichas ou protocolos", groupCode: "D", acceptedTypes: office, primaryAxis: "Bioeconomia", scoringAxes: ["Ambiental", "Social", "Bioeconomia"], points: 3, strategicObjectives: ["Bioeconomia Circular", "Inovação Sustentável"], gapIfMissing: "Prática não comprovada", recommendedService: "Estratégia de bioinsumos sustentáveis" },
  { id: "EV19", name: "Agricultura regenerativa/sustentável", expectedDocument: "Protocolos, registros, fotos ou indicadores", groupCode: "D", acceptedTypes: office, primaryAxis: "Bioeconomia", scoringAxes: ["Ambiental", "Social", "Bioeconomia"], points: 3, strategicObjectives: ["Bioeconomia Circular"], gapIfMissing: "Prática não comprovada", recommendedService: "Programa de agricultura regenerativa" },
  { id: "EV20", name: "Biodiversidade e conservação", expectedDocument: "Plano, registros, mapas, fotos ou monitoramento", groupCode: "B", acceptedTypes: pdfImage, primaryAxis: "Bioeconomia", scoringAxes: ["Ambiental", "Governança", "Bioeconomia"], points: 3, strategicObjectives: ["Certificação Sustentável", "Bioeconomia Circular"], gapIfMissing: "Risco de impacto não monitorado", recommendedService: "Plano de biodiversidade" },
  { id: "EV21", name: "Rastreabilidade de produtos/insumos", expectedDocument: "Sistema, registros, lotes, notas ou plataforma", groupCode: "G", acceptedTypes: office, primaryAxis: "Governança", scoringAxes: ["Ambiental", "Social", "Governança", "Bioeconomia"], points: 3, strategicObjectives: ["Certificação Sustentável", "Bioeconomia Circular", "Captação de Investimentos", "GEE / Scope 3"], gapIfMissing: "Baixa capacidade de rastreamento", recommendedService: "Implantação de rastreabilidade" },
  { id: "EV22", name: "Critérios ESG para fornecedores", expectedDocument: "Política, questionário, contratos ou avaliação", groupCode: "G", acceptedTypes: office, primaryAxis: "Governança", scoringAxes: ["Ambiental", "Social", "Governança", "Bioeconomia"], points: 3, strategicObjectives: ["GEE / Scope 3", "Captação de Investimentos"], gapIfMissing: "Cadeia de fornecedores não gerenciada", recommendedService: "Gestão ESG da cadeia de fornecedores" },
  { id: "EV23", name: "Fornecedores locais/comunitários", expectedDocument: "Cadastro, contratos, notas ou registros", groupCode: "E", acceptedTypes: office, primaryAxis: "Social", scoringAxes: ["Social", "Governança", "Bioeconomia"], points: 2, strategicObjectives: ["Bioeconomia Circular"], gapIfMissing: "Impacto territorial não demonstrado", recommendedService: "Programa de cadeia local" },
  { id: "EV24", name: "Saúde e segurança do trabalho", expectedDocument: "PGR, PCMSO, treinamentos ou registros", groupCode: "E", acceptedTypes: office, primaryAxis: "Social", scoringAxes: ["Social", "Governança"], points: 3, strategicObjectives: ["Certificação Sustentável"], gapIfMissing: "Risco social/trabalhista", recommendedService: "Estruturação de SST" },
  { id: "EV25", name: "Direitos humanos e código de conduta", expectedDocument: "Código, política ou termo de compromisso", groupCode: "F", acceptedTypes: office, primaryAxis: "Social", scoringAxes: ["Social", "Governança"], points: 3, strategicObjectives: ["Certificação Sustentável", "Captação de Investimentos"], gapIfMissing: "Ausência de diretrizes sociais/éticas", recommendedService: "Política ESG e direitos humanos" },
  { id: "EV26", name: "Diversidade e inclusão", expectedDocument: "Política, indicadores, programas ou registros", groupCode: "E", acceptedTypes: office, primaryAxis: "Social", scoringAxes: ["Social", "Governança"], points: 2, strategicObjectives: ["Certificação Sustentável"], gapIfMissing: "Prática não estruturada", recommendedService: "Programa de diversidade e inclusão" },
  { id: "EV27", name: "Capacitação e desenvolvimento", expectedDocument: "Plano, certificados, listas ou registros", groupCode: "E", acceptedTypes: office, primaryAxis: "Social", scoringAxes: ["Social"], points: 1, strategicObjectives: ["Inovação Sustentável"], gapIfMissing: "Baixa evidência de desenvolvimento", recommendedService: "Programa de capacitação ESG" },
  { id: "EV28", name: "Relação com comunidade", expectedDocument: "Projetos, atas, registros, fotos ou indicadores", groupCode: "E", acceptedTypes: office, primaryAxis: "Social", scoringAxes: ["Social", "Governança", "Bioeconomia"], points: 2, strategicObjectives: ["Certificação Sustentável", "Bioeconomia Circular"], gapIfMissing: "Impacto social não comprovado", recommendedService: "Programa de relacionamento territorial" },
  { id: "EV29", name: "Governança e responsabilidades ESG", expectedDocument: "Organograma, atas, comitês ou responsabilidades", groupCode: "F", acceptedTypes: office, primaryAxis: "Governança", scoringAxes: ["Governança"], points: 3, strategicObjectives: ["Captação de Investimentos", "Certificação Sustentável"], gapIfMissing: "ESG sem governança formal", recommendedService: "Estruturação de governança ESG" },
  { id: "EV30", name: "Código de ética/integridade", expectedDocument: "Código, política anticorrupção ou treinamentos", groupCode: "F", acceptedTypes: office, primaryAxis: "Social", scoringAxes: ["Social", "Governança"], points: 2, strategicObjectives: ["Captação de Investimentos"], gapIfMissing: "Risco de governança", recommendedService: "Programa de integridade" },
  { id: "EV31", name: "Canal de denúncias/reclamações", expectedDocument: "Canal, procedimento ou registros", groupCode: "F", acceptedTypes: office, primaryAxis: "Social", scoringAxes: ["Social", "Governança"], points: 2, strategicObjectives: ["Certificação Sustentável"], gapIfMissing: "Mecanismo de controle ausente", recommendedService: "Estruturação de canal de integridade" },
  { id: "EV32", name: "Gestão de riscos ESG", expectedDocument: "Matriz, mapa de riscos ou plano de tratamento", groupCode: "F", acceptedTypes: office, primaryAxis: "Governança", scoringAxes: ["Ambiental", "Social", "Governança", "Bioeconomia"], points: 3, strategicObjectives: ["Captação de Investimentos", "Certificação Sustentável"], gapIfMissing: "Riscos não estruturados", recommendedService: "Matriz de riscos ESG" },
  { id: "EV33", name: "Materialidade e stakeholders", expectedDocument: "Matriz de materialidade, consulta ou relatório", groupCode: "F", acceptedTypes: office, primaryAxis: "Governança", scoringAxes: ["Ambiental", "Social", "Governança", "Bioeconomia"], points: 3, strategicObjectives: ["Captação de Investimentos", "Certificação Sustentável"], gapIfMissing: "Falta de priorização ESG", recommendedService: "Diagnóstico de materialidade ESG" },
  { id: "EV34", name: "Indicadores e relatório ESG", expectedDocument: "Dashboard, relatório ou indicadores", groupCode: "F", acceptedTypes: office, primaryAxis: "Governança", scoringAxes: ["Ambiental", "Social", "Governança", "Bioeconomia"], points: 2, strategicObjectives: ["Captação de Investimentos", "Certificação Sustentável"], gapIfMissing: "Baixa capacidade de mensuração", recommendedService: "Estruturação de indicadores/relatório ESG" },
  { id: "EV35", name: "Gestão financeira e controles", expectedDocument: "Demonstrações, controles, orçamento ou indicadores", groupCode: "F", acceptedTypes: office, primaryAxis: "Governança", scoringAxes: ["Governança"], points: 3, strategicObjectives: ["Captação de Investimentos"], gapIfMissing: "Baixa transparência financeira", recommendedService: "Estruturação de gestão/controles" },
  { id: "EV36", name: "Inovação e P&D", expectedDocument: "Projetos, protocolos, registros ou portfólio", groupCode: "D", acceptedTypes: office, primaryAxis: "Governança", scoringAxes: ["Ambiental", "Social", "Governança", "Bioeconomia"], points: 3, strategicObjectives: ["Inovação Sustentável"], gapIfMissing: "Inovação não estruturada", recommendedService: "Estratégia de inovação sustentável" },
  { id: "EV37", name: "Propriedade intelectual", expectedDocument: "Patentes, registros, contratos ou ativos", groupCode: "F", acceptedTypes: office, primaryAxis: "Governança", scoringAxes: ["Governança", "Bioeconomia"], points: 2, strategicObjectives: ["Inovação Sustentável", "Captação de Investimentos"], gapIfMissing: "Ativos de inovação não protegidos", recommendedService: "Estratégia de PI/ativos tecnológicos" },
  { id: "EV38", name: "Parcerias para inovação", expectedDocument: "Convênios, contratos ou projetos com ICTs", groupCode: "F", acceptedTypes: office, primaryAxis: "Social", scoringAxes: ["Social", "Governança", "Bioeconomia"], points: 2, strategicObjectives: ["Inovação Sustentável"], gapIfMissing: "Baixa articulação de inovação", recommendedService: "Estruturação de parcerias" },
  { id: "EV39", name: "Impacto socioambiental e bioeconômico", expectedDocument: "Indicadores, estudos, resultados ou casos", groupCode: "F", acceptedTypes: office, primaryAxis: "Social", scoringAxes: ["Ambiental", "Social", "Governança", "Bioeconomia"], points: 3, strategicObjectives: ["Captação de Investimentos", "Bioeconomia Circular"], gapIfMissing: "Impacto não mensurado", recommendedService: "Mensuração de impacto ESG-Bio" },
  { id: "EV40", name: "Evidências complementares de práticas", expectedDocument: "Fotos, certificados, atas, campanhas ou comunicações", groupCode: "H", acceptedTypes: pdfImage, primaryAxis: "Governança", scoringAxes: ["Ambiental", "Social", "Governança", "Bioeconomia"], points: 1, strategicObjectives: ["Certificação Sustentável", "Bioeconomia Circular", "Inovação Sustentável", "Captação de Investimentos", "GEE / Scope 3"], gapIfMissing: "Apenas ausência de reforço documental", recommendedService: "Não necessariamente gera serviço" },
];

export const EVIDENCE_DOCUMENTS_MOCK = agroEvidences.reduce<Record<EvidenceAxis, AgroEvidence[]>>((result, document) => {
  result[document.primaryAxis].push(document);
  return result;
}, { Ambiental: [], Bioeconomia: [], Social: [], Governança: [] });

export const ALL_EVIDENCE_DOCUMENTS_MOCK = agroEvidences;
