import type {
  AdminAnalyticsBoardModel,
  AdminBudgetBoardModel,
  AdminBudgetRequest,
  AdminClientBoardModel,
  AdminClientSummary,
  AdminEvidenceBoardModel,
  AdminEvidenceSummary,
  AdminInsightCard,
  AdminMetric,
  AdminSupplierBoardModel,
  AdminSupplierSummary,
  AdminAxisInsight,
} from "./types";

export const adminBudgetRequests: AdminBudgetRequest[] = [
  {
    id: "bud-001",
    organizationName: "Inove Alimentos S.A.",
    legalName: "Inove Alimentos S.A.",
    sector: "Indústria de alimentos",
    employeeCount: "251-500",
    annualRevenue: "R$ 60 mi - R$ 120 mi",
    objective: "Diagnóstico ESG + plano de ação",
    timeline: "0-30 dias",
    focusAreas: ["E", "B", "S", "G"],
    hasPriorInventory: "Sim",
    phone: "(11) 98888-1000",
    notes: "Queremos proposta com fase inicial e evidências prioritárias.",
    proposalValue: "R$ 38.500,00",
    status: "PENDING",
    createdAt: "18 jun 2026",
    updatedAt: "18 jun 2026",
    tags: ["prioridade alta", "pre-diagnóstico", "renovação"],
  },
  {
    id: "bud-002",
    organizationName: "Verde Campo LTDA",
    legalName: "Verde Campo LTDA",
    sector: "Agronegócio",
    employeeCount: "51-100",
    annualRevenue: "R$ 12 mi - R$ 24 mi",
    objective: "Diagnóstico ESG + fornecedores",
    timeline: "30-60 dias",
    focusAreas: ["E", "S", "G"],
    hasPriorInventory: "Não",
    phone: "(19) 97777-2000",
    notes: "Precisa de estimativa para implantação e convites de cadeia.",
    proposalValue: "R$ 22.900,00",
    status: "IN_REVIEW",
    createdAt: "17 jun 2026",
    updatedAt: "18 jun 2026",
    tags: ["novo cliente", "cadeia ativa"],
  },
  {
    id: "bud-003",
    organizationName: "EcoLog Transportes",
    legalName: "EcoLog Transportes e Logística S.A.",
    sector: "Logística & Transportes",
    employeeCount: "500+",
    annualRevenue: "R$ 120 mi+",
    objective: "Relatório executivo + inventário",
    timeline: "0-15 dias",
    focusAreas: ["E", "B"],
    hasPriorInventory: "Sim",
    phone: "(21) 96666-3000",
    notes: null,
    proposalValue: "R$ 49.800,00",
    status: "PROPOSAL_SENT",
    createdAt: "16 jun 2026",
    updatedAt: "18 jun 2026",
    tags: ["maior ticket", "expediente rápido"],
  },
  {
    id: "bud-004",
    organizationName: "Casa Nova Construtora",
    legalName: "Casa Nova Construtora e Engenharia LTDA",
    sector: "Construção Civil",
    employeeCount: "101-250",
    annualRevenue: "R$ 24 mi - R$ 60 mi",
    objective: "Primeiro diagnóstico ESG",
    timeline: "60-90 dias",
    focusAreas: ["E", "S", "G"],
    hasPriorInventory: "Não",
    phone: "(31) 95555-4000",
    notes: "Solicitou abordagem com etapa de sensibilização.",
    proposalValue: "R$ 17.500,00",
    status: "REJECTED",
    createdAt: "14 jun 2026",
    updatedAt: "17 jun 2026",
    tags: ["sem inventário", "precisa educação"],
  },
  {
    id: "bud-005",
    organizationName: "BioEnergia Sul",
    legalName: "BioEnergia Sul S.A.",
    sector: "Óleo e Gás",
    employeeCount: "500+",
    annualRevenue: "R$ 120 mi+",
    objective: "Auditoria ESG e evidências",
    timeline: "15-30 dias",
    focusAreas: ["E", "B", "G"],
    hasPriorInventory: "Sim",
    phone: "(41) 94444-5000",
    notes: "Requer aprovação do conselho antes do fechamento.",
    proposalValue: "R$ 61.200,00",
    status: "APPROVED",
    createdAt: "12 jun 2026",
    updatedAt: "18 jun 2026",
    tags: ["fechado", "alta complexidade"],
  },
];

export const adminClients: AdminClientSummary[] = [
  {
    id: "cli-001",
    tradeName: "Inove Alimentos S.A.",
    legalName: "Inove Alimentos S.A.",
    segment: "Indústria de alimentos",
    plan: "Growth ESG",
    diagnosticStatus: "COMPLETED",
    health: "watch",
    lastDiagnosticAt: "18 jun 2026",
    score: 72,
    evidencePending: 7,
    supplierCoverage: "61%",
    activeUsers: 4,
  },
  {
    id: "cli-002",
    tradeName: "Verde Campo LTDA",
    legalName: "Verde Campo LTDA",
    segment: "Agronegócio",
    plan: "Consultoria",
    diagnosticStatus: "CONTRACTED",
    health: "healthy",
    lastDiagnosticAt: "17 jun 2026",
    score: 84,
    evidencePending: 2,
    supplierCoverage: "88%",
    activeUsers: 3,
  },
  {
    id: "cli-003",
    tradeName: "Casa Nova Construtora",
    legalName: "Casa Nova Construtora e Engenharia LTDA",
    segment: "Construção Civil",
    plan: "Starter ESG",
    diagnosticStatus: "DRAFT",
    health: "critical",
    lastDiagnosticAt: "14 jun 2026",
    score: 41,
    evidencePending: 14,
    supplierCoverage: "22%",
    activeUsers: 2,
  },
  {
    id: "cli-004",
    tradeName: "EcoLog Transportes",
    legalName: "EcoLog Transportes e Logística S.A.",
    segment: "Logística & Transportes",
    plan: "Enterprise",
    diagnosticStatus: "COMPLETED",
    health: "healthy",
    lastDiagnosticAt: "16 jun 2026",
    score: 79,
    evidencePending: 4,
    supplierCoverage: "70%",
    activeUsers: 6,
  },
];

export const adminSuppliers: AdminSupplierSummary[] = [
  {
    id: "sup-001",
    companyName: "Forn. Verde Orgânico",
    contactEmail: "contato@verdeorganico.com",
    segment: "Agronegócio",
    status: "RESPONDED",
    progress: 100,
    score: 81,
    evidencePending: 0,
    invitedAt: "10 jun 2026",
    lastUpdate: "18 jun 2026",
  },
  {
    id: "sup-002",
    companyName: "Polo Logística Sul",
    contactEmail: "esg@polosul.com",
    segment: "Logística & Transportes",
    status: "ACTIVE",
    progress: 68,
    score: 63,
    evidencePending: 3,
    invitedAt: "11 jun 2026",
    lastUpdate: "17 jun 2026",
  },
  {
    id: "sup-003",
    companyName: "Metal Forte Components",
    contactEmail: "sustentabilidade@metaforte.com",
    segment: "Indústria Metal-Mecânica",
    status: "INVITED",
    progress: 0,
    score: 0,
    evidencePending: 0,
    invitedAt: "16 jun 2026",
    lastUpdate: "16 jun 2026",
  },
  {
    id: "sup-004",
    companyName: "BioCircular Pack",
    contactEmail: "eco@biocircularpack.com",
    segment: "Química & Plásticos",
    status: "OVERDUE",
    progress: 42,
    score: 49,
    evidencePending: 5,
    invitedAt: "08 jun 2026",
    lastUpdate: "13 jun 2026",
  },
  {
    id: "sup-005",
    companyName: "AgroPrime Serviços",
    contactEmail: "admin@agroprime.com",
    segment: "Agronegócio",
    status: "ACTIVE",
    progress: 75,
    score: 74,
    evidencePending: 1,
    invitedAt: "09 jun 2026",
    lastUpdate: "18 jun 2026",
  },
];

export const adminEvidences: AdminEvidenceSummary[] = [
  {
    id: "ev-001",
    title: "Licença ambiental vigente",
    companyName: "Inove Alimentos S.A.",
    supplierName: "Forn. Verde Orgânico",
    axis: "E",
    questionCode: "q-1",
    status: "PENDING",
    uploadDate: "18 jun 2026",
    reviewer: "Aguardando",
    fileName: "licenca_ambiental_2026.pdf",
    severity: "high",
  },
  {
    id: "ev-002",
    title: "Programa de segurança operacional",
    companyName: "EcoLog Transportes",
    supplierName: "Polo Logística Sul",
    axis: "S",
    questionCode: "q-12",
    status: "UNDER_REVIEW",
    uploadDate: "17 jun 2026",
    reviewer: "Mariana",
    fileName: "seguranca_operacional.zip",
    severity: "medium",
  },
  {
    id: "ev-003",
    title: "Canal de denúncias documentado",
    companyName: "Casa Nova Construtora",
    supplierName: "Metal Forte Components",
    axis: "G",
    questionCode: "q-29",
    status: "VERIFIED",
    uploadDate: "16 jun 2026",
    reviewer: "Rafael",
    fileName: "canal_denuncias.docx",
    severity: "low",
  },
  {
    id: "ev-004",
    title: "Rastreabilidade de insumos",
    companyName: "Inove Alimentos S.A.",
    supplierName: "AgroPrime Serviços",
    axis: "B",
    questionCode: "q-41",
    status: "PENDING",
    uploadDate: "15 jun 2026",
    reviewer: "Aguardando",
    fileName: "rastreabilidade.xlsx",
    severity: "high",
  },
  {
    id: "ev-005",
    title: "Plano de metas e indicadores",
    companyName: "Verde Campo LTDA",
    supplierName: "BioCircular Pack",
    axis: "B",
    questionCode: "q-48",
    status: "REJECTED",
    uploadDate: "12 jun 2026",
    reviewer: "Carla",
    fileName: "metas_e_indicadores.pdf",
    severity: "medium",
  },
];

export const adminAxisInsights: AdminAxisInsight[] = [
  { axis: "E", label: "Ambiental", score: 72, responseRate: 86, evidenceCoverage: 68, pendingItems: 11, trend: 5 },
  { axis: "B", label: "Bioeconomia Circular", score: 61, responseRate: 74, evidenceCoverage: 55, pendingItems: 14, trend: 8 },
  { axis: "S", label: "Social", score: 79, responseRate: 91, evidenceCoverage: 72, pendingItems: 6, trend: 3 },
  { axis: "G", label: "Governança", score: 66, responseRate: 83, evidenceCoverage: 64, pendingItems: 9, trend: 4 },
];

export const adminTrend = [
  { label: "Jan", value: 42 },
  { label: "Fev", value: 46 },
  { label: "Mar", value: 54 },
  { label: "Abr", value: 61 },
  { label: "Mai", value: 68 },
  { label: "Jun", value: 74 },
];

export const adminMetrics: AdminMetric[] = [
  { id: "budgets-open", label: "Orçamentos em aberto", value: "5", detail: "2 aguardando revisão", tone: "amber" },
  { id: "clients-active", label: "Clientes ativos", value: "4", detail: "1 em risco de renovação", tone: "emerald" },
  { id: "evidence-pending", label: "Evidências pendentes", value: "32", detail: "18 em revisão técnica", tone: "rose" },
  { id: "suppliers-responded", label: "Fornecedores respondidos", value: "3/5", detail: "60% de resposta na base", tone: "slate" },
];

export const adminBudgetBoardModel: AdminBudgetBoardModel = {
  metrics: adminMetrics,
  requests: adminBudgetRequests,
  groupedByStatus: {
    PENDING: 1,
    IN_REVIEW: 1,
    PROPOSAL_SENT: 1,
    APPROVED: 1,
    REJECTED: 1,
  },
  openValue: "R$ 190.900,00",
};

export const adminClientBoardModel: AdminClientBoardModel = {
  metrics: [
    { id: "avg-score", label: "Score médio", value: "69", detail: "Base cliente atual", tone: "emerald" },
    { id: "renewal-risk", label: "Risco de renovação", value: "1", detail: "Conta com maturidade crítica", tone: "amber" },
    { id: "diagnostics-completed", label: "Diagnósticos concluídos", value: "2", detail: "Entre 4 contas ativas", tone: "slate" },
    { id: "active-users", label: "Usuários ativos", value: "15", detail: "Acesso distribuído por operação", tone: "emerald" },
  ],
  clients: adminClients,
  healthDistribution: {
    healthy: 2,
    watch: 1,
    critical: 1,
  },
};

export const adminSupplierBoardModel: AdminSupplierBoardModel = {
  metrics: [
    { id: "supplier-base", label: "Fornecedores na base", value: "5", detail: "3 em andamento", tone: "slate" },
    { id: "response-rate", label: "Taxa de resposta", value: "60%", detail: "Base convidada", tone: "emerald" },
    { id: "avg-score", label: "Score médio", value: "53", detail: "Somente respondidos", tone: "amber" },
    { id: "evidence-gap", label: "Evidências pendentes", value: "9", detail: "Itens sem validação", tone: "rose" },
  ],
  suppliers: adminSuppliers,
  pipeline: {
    INVITED: 1,
    ACTIVE: 2,
    RESPONDED: 1,
    OVERDUE: 1,
  },
};

export const adminEvidenceBoardModel: AdminEvidenceBoardModel = {
  metrics: [
    { id: "evidence-total", label: "Evidências em fila", value: "5", detail: "2 críticas", tone: "amber" },
    { id: "evidence-verified", label: "Validadas", value: "1", detail: "20% do total", tone: "emerald" },
    { id: "evidence-rejected", label: "Rejeitadas", value: "1", detail: "Reenvio necessário", tone: "rose" },
    { id: "reviewers", label: "Revisores ativos", value: "3", detail: "Cobertura da fila", tone: "slate" },
  ],
  evidences: adminEvidences,
  reviewDistribution: {
    PENDING: 2,
    UNDER_REVIEW: 1,
    VERIFIED: 1,
    REJECTED: 1,
  },
};

export const adminAnalyticsBoardModel: AdminAnalyticsBoardModel = {
  metrics: [
    { id: "global-score", label: "Score médio consolidado", value: "69", detail: "Base de diagnósticos ativos", tone: "emerald" },
    { id: "proven-gap", label: "Gap comprovado", value: "18", detail: "Diferença entre declarado e validado", tone: "amber" },
    { id: "time-to-close", label: "Tempo médio de fechamento", value: "9 dias", detail: "Da abertura ao envio", tone: "slate" },
    { id: "evidence-coverage", label: "Cobertura de evidências", value: "64%", detail: "Média ponderada por pilar", tone: "rose" },
  ],
  axisInsights: adminAxisInsights,
  trend: adminTrend,
  maturityBands: [
    { label: "Inicial", value: 14, tone: "rose" },
    { label: "Básico", value: 26, tone: "amber" },
    { label: "Estruturado", value: 34, tone: "slate" },
    { label: "Avançado", value: 18, tone: "emerald" },
  ],
  notes: [
    {
      title: "Bioeconomia ainda com baixa cobertura",
      description: "O pilar B concentra o maior gap de evidências e requer revisão de perguntas com peso maior.",
      tone: "amber",
    },
    {
      title: "Clientes em risco concentrados em construção",
      description: "A conta com menor maturidade possui diagnóstico incompleto e fila de evidências crítica.",
      tone: "rose",
    },
    {
      title: "Fornecedores respondendo bem",
      description: "A cadeia convidada mantém boa taxa de resposta, com maior atraso em duas contas específicas.",
      tone: "emerald",
    },
  ],
};
